version: '3.8'


services:


  db:
    image: ghcr.io/baosystems/postgis:latest
    environment:
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: secret
      TZ: UTC
    volumes:
      - staybooking-pg-local:/var/lib/postgresql/data
    ports:
      - "5432:5432"


volumes:
  staybooking-pg-local:
